volumes:
  weather_bot_data:
  postgres_data:
  redis_data:

x-app: &app
  logging:
    driver: "json-file"
    options:
      max-file: "3"
      max-size: "10m"
  env_file:
    - .env
  restart: no

services:
  postgres:
    <<: *app
    image: postgres:14.0
    environment:
      - TZ=Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    <<: *app
    image: redis:7.2.5
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./src/frameworks_and_drivers/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:6379
    restart: unless-stopped  

  weather_bot:
    <<: *app
    container_name: weather_bot
    build:
      context: ./
      dockerfile: src/Dockerfile
    environment:
      TZ: Europe/Moscow
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      TOKEN: ${TOKEN}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    volumes:
      - weather_bot_data:/opt/app/src/db/